### ISSUE TITLE
🎨 ItemTappedView, ProfileTappedView의 동적 텍스트 크기 지정, 동적 스크롤 영역 지정, 코드 구조 개선 등을 수행합니다.

### ISSUE THREAD

**Issue by Rookie0031** [DeveloperAcademy-POSTECH/MacC-Dime-Vincent#31]
## 개요
ItemTappedView, ProfileTappedView의 동적 텍스트 크기 지정, 동적 스크롤 영역 지정, 코드 구조 개선 등을 수행합니다. (제곧내)

## Todo List
- [ ] 이미지 정방형 맞추기
- [ ] 스크롤뷰 사이즈 동적 지정 
- [ ] 텍스트 동적 지정

## ProfileTappedView
- [ ] 이미지 정방형 맞추기 
- [ ] 텍스트 동적 지정 

## ItemTappedViewReport
- [ ] corner radius 동적으로 지정하기 

by 10.13
