### ISSUE TITLE
🎨 MainView에서 임시로 들어가 있는 개체들을 실제 서비스에 맞게 다듬겠습니다.

### ISSUE THREAD

**Issue by obtusa07** [DeveloperAcademy-POSTECH/MacC-Dime-Vincent#36]
## 개요
현재 HomeVIew는 파란색 화면의 사각형으로 임시 레이아웃을 배치한 상황입니다. 
이를 디자인 원안에 가깝게 구현하면서 현재 해당 부분이 그레이로 디자인 되어 있기 때문에 다른 View를 참고하여 적절한 모습을 그리도록 만들겠습니다.

### View의 목적
유저는 Category 관련 기능을 사용하려고 할때 해당 기능으로 분류된 View를 불러옵니다.

## Task
- [ ] 카테고리와 최신 물품의 배경에 검은색으로 카드 디자인 적용
- [ ] 카테고리 Section에 image와 Label을 가지는 Item cell 디자인과 배치
- [ ] 최신상품 Section에 Image, 복수의 Label을 가지는 Item Cell 디자인과 배치

## Consideration
1. Compositional Layout으로 화면을 그리게 되면 기존에 구현해놓은 Cell과 데이터 구조를 Diffable Datasource, snapshot으로 관리하고자 합니다. 개발하고자 하는 아이템이 활발하게 리뉴얼되거나 상태변경이 중요한 중고거래이기 때문에 Single Source of Truth을 고려하여 개발하는것이 저희 팀 입장에서 더 쉽고 안전하게 개발할 수 있다는 판단을 했습니다.
2. 해당 방법으로 모든 카테고리와 Cell을 바꾸면서 더 쉽게 다른 분들이 가져다 쓸수 있도록 PR을 신경 써서 작성하겠습니다. 현재 ScrollView와 다른 View에서 데이터를 처리하는 방법에 대한 고민이 많은거 같습니다.

### Related View(Optional)

- HomeView
- CategoryTappedView

### 우선순위

★★★★★

### 예상 작업 기간

2022.10.14 ~ 10.17
